import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import AuthProviders from "@/lib/AuthProvider";
import ProgressBarProvider from "@/lib/ProgressBar";
import Script from "next/script";
import { nextGetServerSession } from "@/lib/authOption";
import { NewNavbar } from "@/app/components/utils/navigate";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

// const geistSans = localFont({
//   src: "../fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "../fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await nextGetServerSession();
  if (!session) console.log("no session");
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <AuthProviders>
          <ProgressBarProvider>
            {/* {session ? <Navbar /> : <Sidebar />} */}
            <NewNavbar />
            {children}
          </ProgressBarProvider>
        </AuthProviders>
        <Script
          src="https://app.sandbox.midtrans.com/snap/snap.js"
          data-client-key={process.env.NEXT_PUBLIC_MIDTRANS_CLIENT_KEY}
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
